# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c409313ea7260cc1bead74bac0b8a1f0fa34c49ce00a65a98c90a2d88b06fb424dd5c81e60316c5ab1b1ef7052c2ff4455f46265e7d0f1762ecdaf9001121c5

test:
  secret_key_base: 18e01baac642e4e0a106bb4dba2564b3b739ed8629124c33e251d2cf8ddfad75aaa5c9213d1eada3e296b12a9741cca6b1b6c0aea3d11fa934cd947ed2166e41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
